repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  -   id: check-yaml
  -   id: end-of-file-fixer
      exclude: .example$
  -   id: trailing-whitespace
      exclude: .example$

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.8.0
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
    - id: ruff-format

- repo: local
  hooks:
    - id: pytest
      name: pytest
      entry: bash -c "cd python && uvx --with-requirements pyproject.toml pytest"
      language: system
      pass_filenames: false
      always_run: true
